services:
  mysql-db:
    image: mysql:8.0
    container_name: contenedor_mysql_ventas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_ventas
      MYSQL_USER: user_ventas
      MYSQL_PASSWORD: user12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_limpio:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: contenedor_app_ventas
    restart: on-failure
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/db_ventas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user_ventas
      SPRING_DATASOURCE_PASSWORD: user12345

volumes:
  mysql_data_limpio: