version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: contenedor_mysql_ventas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_ventas
      MYSQL_USER: user_ventas
      MYSQL_PASSWORD: user12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: