# Conexión local desde IntelliJ al puerto expuesto de Docker
spring.datasource.url=jdbc:mysql://localhost:3306/db_ventas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=user_ventas
spring.datasource.password=user12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración básica de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.main.web-application-type=servlet

# Soluciona la compatibilidad con Swagger 3
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Dejamos que Hibernate maneje el esquema de forma diferida
spring.jpa.defer-datasource-initialization=true

# 🔥 NUEVA LÍNEA: obliga a Spring Boot a ejecutar import.sql siempre, sin importar ddl-auto
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:import.sql